version: "3.5"

services:
  #############################
  # Trips Step Parser
  #############################
  trips-step:
    tty: true
    privileged: true
    build:
      context: ./container_trips/
      dockerfile: Dockerfile
      network: host
    network_mode: "host"
    ports:
      - 6200:6200
    volumes:
      - ./container_trips/volume:/vagrant
    environment:
      - "CPORT=6200"
